# Generated by Django 4.0.1 on 2022-01-20 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='x',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='y',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(125.0)]),
        ),
    ]
